/**
 * CAMPAIGN_RECIPES — Phase 3's real recipe library for the new campaign
 * (brief §2/§24/§26): ~35 honestly-authored, named dishes covering
 * Chapters 1-4 (Levels 1-40). Every ingredient/technique combination here
 * is checked against `INGREDIENTS[id].techniques` in definitions.ts — no
 * recipe asks for a cut the engine doesn't actually support for that
 * ingredient (e.g. no tomato radial, no zucchini/potato/asparagus/
 * mushroom julienne, no apple halve — those ingredients simply don't
 * list that technique).
 *
 * Authenticity (§25): "A" only where the simplified dish is a real,
 * recognizable version of something people actually make with these
 * ingredients (bruschetta, caprese, minestrone base, French onion base).
 * "B" for KnifeCraft-invented service scenarios (a branching/shared-
 * output/batching demo dressed as a dish) that aren't claiming to BE a
 * traditional recipe.
 *
 * `cuisineId` is real here (unlike deriveRecipeFromLevel's `null` for
 * the OLD 1-120 content) — these are freshly authored for the new
 * campaign, so retroactive-mislabeling concerns (§66 of the earlier
 * brief) don't apply.
 *
 * Recipes are deliberately REUSED across levels (§3/§26) rather than
 * one-recipe-per-level — see levelDefinitions.ts's `recipePoolIds` on
 * Levels 24/30/40, which point at recipes first introduced earlier.
 */
import type { RecipeDefinition } from "./recipeTypes";

const PLATE = { id: "plate", name: "Plate" };
const BOWL = { id: "bowl", name: "Bowl" };

export const CAMPAIGN_RECIPES: RecipeDefinition[] = [
  // ───────────────────────── Chapter 1 — Opening the Restaurant ─────────────────────────
  {
    id: "camp-sliced-tomato-plate",
    name: "Sliced Tomato Plate",
    emoji: "🍅",
    cuisineId: null,
    authenticity: "B",
    components: [
      {
        ingredientId: "tomato",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Slice the tomato into clean, even rounds.",
    customerDialogue: "Something simple to start, please.",
    basePayment: 50,
    unlockLevel: 1,
  },
  {
    id: "camp-fresh-cucumber-plate",
    name: "Fresh Cucumber Plate",
    emoji: "🥒",
    cuisineId: null,
    authenticity: "B",
    components: [
      {
        ingredientId: "cucumber",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Slice the cucumber into rounds.",
    customerDialogue: "Something light and crisp, if you have it.",
    basePayment: 52,
    unlockLevel: 2,
  },
  {
    id: "camp-carrot-chop-bowl",
    name: "Carrot Chop Bowl",
    emoji: "🥕",
    cuisineId: null,
    authenticity: "B",
    components: [
      {
        ingredientId: "carrot",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Chop the carrot into short, even pieces.",
    customerDialogue: "Whatever's freshest today.",
    basePayment: 55,
    unlockLevel: 3,
  },
  {
    id: "camp-garden-tomato-cucumber",
    name: "Garden Tomato & Cucumber Plate",
    emoji: "🥗",
    cuisineId: null,
    authenticity: "A",
    components: [
      {
        ingredientId: "tomato",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "cucumber",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction: "Slice the tomato, then slice the cucumber the same way.",
    customerDialogue: "The garden plate — tomato and cucumber, please.",
    basePayment: 60,
    unlockLevel: 4,
  },
  {
    id: "camp-onion-prep-chain",
    name: "Onion Prep",
    emoji: "🧅",
    cuisineId: null,
    authenticity: "A",
    components: [
      {
        ingredientId: "onion",
        technique: "peel",
        resultingState: "peeled",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "onion",
        technique: "halve",
        resultingState: "halved",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "onion",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Peel the onion, halve it, then slice it thin.",
    customerDialogue: "Just the prepped onion, for the pot.",
    basePayment: 64,
    unlockLevel: 5,
  },
  {
    id: "camp-diced-tomato-cup",
    name: "Diced Tomato Cup",
    emoji: "🍅",
    cuisineId: null,
    authenticity: "B",
    components: [
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: true,
    chefInstruction: "Dice the tomato into a neat, even grid.",
    customerDialogue: "Diced tomato, for the soup base.",
    basePayment: 62,
    unlockLevel: 6,
  },
  {
    id: "camp-peeled-potato-bowl",
    name: "Peeled Potato Bowl",
    emoji: "🥔",
    cuisineId: null,
    authenticity: "B",
    components: [
      {
        ingredientId: "potato",
        technique: "peel",
        resultingState: "peeled",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Peel the potato clean.",
    customerDialogue: "Just the peeled potato, please.",
    basePayment: 60,
    unlockLevel: 7,
  },
  {
    id: "camp-halved-potato-bowl",
    name: "Halved Potato Bowl",
    emoji: "🥔",
    cuisineId: null,
    authenticity: "B",
    components: [
      {
        ingredientId: "potato",
        technique: "halve",
        resultingState: "halved",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Halve the potato evenly.",
    customerDialogue: "Halved potato, ready for the pan.",
    basePayment: 63,
    unlockLevel: 8,
  },
  {
    id: "camp-smashed-garlic-prep",
    name: "Smashed Garlic Prep",
    emoji: "🧄",
    cuisineId: null,
    authenticity: "A",
    components: [
      {
        ingredientId: "garlic",
        technique: "smash",
        resultingState: "smashed",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Smash the garlic clove flat.",
    customerDialogue: "The garlic, smashed — for the base.",
    basePayment: 65,
    unlockLevel: 9,
  },
  {
    id: "camp-simple-garden-salad",
    name: "Simple Garden Salad",
    emoji: "🥙",
    cuisineId: null,
    authenticity: "A",
    components: [
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "cucumber",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "carrot",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction:
      "Dice the tomato, slice the cucumber, then chop the carrot — all onto one plate.",
    customerDialogue: "The garden salad — the whole thing, please.",
    basePayment: 80,
    unlockLevel: 10,
  },

  // ───────────────────────── Chapter 2 — Italian Kitchen ─────────────────────────
  {
    id: "camp-garlic-bread",
    name: "Garlic Bread",
    emoji: "🍞",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "bread",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "garlic",
        technique: "smash",
        resultingState: "smashed",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Slice the bread, then smash the garlic to rub over it.",
    customerDialogue: "Garlic bread, the way the house makes it.",
    basePayment: 72,
    unlockLevel: 11,
  },
  {
    id: "camp-tomato-basil-toast",
    name: "Tomato Basil Toast",
    emoji: "🍅",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "bread",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "basil",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction: "Slice the bread, dice the tomato, then chop the basil over the top.",
    customerDialogue: "Tomato basil toast, please.",
    basePayment: 85,
    unlockLevel: 12,
  },
  {
    id: "camp-mushroom-bruschetta",
    name: "Mushroom Bruschetta",
    emoji: "🍄",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "bread",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "mushroom",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "garlic",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Slice the bread, slice the mushrooms, then chop the garlic through them.",
    customerDialogue: "The mushroom bruschetta, if the mushrooms are good today.",
    basePayment: 90,
    unlockLevel: 13,
  },
  {
    id: "camp-zucchini-garden-plate",
    name: "Zucchini Garden Plate",
    emoji: "🥒",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "zucchini",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "carrot",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Slice the zucchini, then dice the carrot alongside it.",
    customerDialogue: "Something green and simple.",
    basePayment: 88,
    unlockLevel: 14,
  },
  {
    id: "camp-caprese-plate",
    name: "Caprese Plate",
    emoji: "🧀",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "tomato",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "mozzarella",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "basil",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction: "Slice the tomato and the mozzarella, then chop the basil over both.",
    customerDialogue: "Caprese, please — the classic.",
    basePayment: 95,
    unlockLevel: 15,
  },
  {
    id: "camp-onion-rings-basket",
    name: "Onion Rings Basket",
    emoji: "🧅",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "onion",
        technique: "rings",
        resultingState: "ringed",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Cut the onion into even rings.",
    customerDialogue: "A basket of onion rings, please.",
    basePayment: 90,
    unlockLevel: 16,
  },
  {
    id: "camp-garden-minestrone-base",
    name: "Garden Minestrone Base",
    emoji: "🍲",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "carrot",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "zucchini",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: true,
    chefInstruction: "Dice the tomato, chop the carrot, then slice the zucchini into the pot.",
    customerDialogue: "The minestrone, if there's a fresh batch.",
    basePayment: 100,
    unlockLevel: 17,
  },
  {
    id: "camp-bruschetta-for-the-house",
    name: "Bruschetta for the House",
    emoji: "🍞",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "bread",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "garlic",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "basil",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction:
      "Slice the bread, dice the tomato, chop the garlic, then chop the basil — everything onto one plate.",
    customerDialogue: "The full bruschetta, please — don't skip anything.",
    basePayment: 110,
    unlockLevel: 18,
  },
  {
    id: "camp-mozzarella-tomato-skewers",
    name: "Mozzarella & Tomato Skewers",
    emoji: "🍢",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "tomato",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "mozzarella",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction: "Slice the tomato and the mozzarella the same thickness.",
    customerDialogue: "The little skewers, please.",
    basePayment: 92,
    unlockLevel: 19,
  },
  {
    id: "camp-italian-garden-plate",
    name: "Italian Garden Plate",
    emoji: "🇮🇹",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "zucchini",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "basil",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "onion",
        technique: "rings",
        resultingState: "ringed",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction:
      "Dice the tomato, slice the zucchini, chop the basil, then ring the onion — the full plate.",
    customerDialogue: "The whole Italian garden plate, please.",
    basePayment: 130,
    unlockLevel: 20,
  },

  // ───────────────────────── Chapter 3 — Italian Service ─────────────────────────
  {
    id: "camp-julienne-carrot-garnish",
    name: "Julienne Carrot Garnish",
    emoji: "🥕",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "carrot",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Julienne the carrot into fine, even batons.",
    customerDialogue: "Just a garnish — something fine and neat.",
    basePayment: 95,
    unlockLevel: 21,
  },
  {
    id: "camp-julienne-pepper-ribbons",
    name: "Julienne Pepper Ribbons",
    emoji: "🫑",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "pepper",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Julienne the pepper into thin ribbons.",
    customerDialogue: "Pepper ribbons, for the antipasto.",
    basePayment: 98,
    unlockLevel: 22,
  },
  {
    id: "camp-orange-rose-garnish",
    name: "Orange Rose Garnish",
    emoji: "🍊",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "orange",
        technique: "radial",
        resultingState: "wedged",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Cut the orange into an even rose of wedges for the plate.",
    customerDialogue: "Whatever makes the plate look beautiful.",
    basePayment: 100,
    unlockLevel: 23,
  },
  {
    id: "camp-caprese-skewers-batch",
    name: "Caprese Skewers Batch",
    emoji: "🍢",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "tomato",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "mozzarella",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction: "Slice the tomato, slice the mozzarella — the same cut the caprese uses.",
    customerDialogue: "A batch of the skewers, if you're already making them.",
    basePayment: 100,
    unlockLevel: 25,
  },
  {
    id: "camp-bruschetta-trio",
    name: "Bruschetta Trio",
    emoji: "🍞",
    cuisineId: "italian",
    authenticity: "A",
    components: [
      {
        ingredientId: "bread",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "basil",
        technique: "chop",
        resultingState: "chopped",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction:
      "Slice the bread, dice the tomato — the same cut as the other order — then chop the basil.",
    customerDialogue: "The bruschetta trio, please.",
    basePayment: 105,
    unlockLevel: 12,
  },
  {
    id: "camp-garden-tomato-cup",
    name: "Garden Tomato Cup",
    emoji: "🥣",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "cucumber",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: true,
    chefInstruction: "Dice the tomato — the same cut as the bruschetta — then slice the cucumber.",
    customerDialogue: "A garden cup, extra tomato.",
    basePayment: 95,
    unlockLevel: 6,
  },
  {
    id: "camp-julienne-vegetable-medley",
    name: "Julienne Vegetable Medley",
    emoji: "🥗",
    cuisineId: "italian",
    authenticity: "B",
    components: [
      {
        ingredientId: "carrot",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "pepper",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "cucumber",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Julienne the carrot, the pepper, and the cucumber — all the same fine cut.",
    customerDialogue: "The vegetable medley, please — as fine as you can cut it.",
    basePayment: 130,
    unlockLevel: 27,
  },
  {
    id: "camp-onion-two-ways",
    name: "Onion Two Ways",
    emoji: "🧅",
    cuisineId: "italian",
    authenticity: "B",
    // Branching demo (brief §18/§19): one ingredient, two independent
    // cuts, two destinations — chainBreak on the second because it's a
    // fresh onion, not a continuation of the first cut.
    components: [
      {
        ingredientId: "onion",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["bruschetta"],
      },
      {
        ingredientId: "onion",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["soup"],
        chainBreak: true,
      },
    ],
    destinations: [
      { id: "bruschetta", name: "Bruschetta" },
      { id: "soup", name: "Soup Base" },
    ],
    batchable: false,
    chefInstruction: "Slice one onion for the bruschetta, then dice a fresh one for the soup base.",
    customerDialogue: "Prepare the onion, then split it between the two.",
    basePayment: 120,
    unlockLevel: 28,
  },
  {
    id: "camp-family-antipasto-for-two",
    name: "Family Antipasto for Two",
    emoji: "🍽️",
    cuisineId: "italian",
    authenticity: "B",
    // Shared-output demo (brief §20/§24): one batch, two named plates.
    components: [
      {
        ingredientId: "bread",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate-a", "plate-b"],
      },
      {
        ingredientId: "tomato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["plate-a", "plate-b"],
      },
    ],
    destinations: [
      { id: "plate-a", name: "Maya's Plate" },
      { id: "plate-b", name: "Daniel's Plate" },
    ],
    batchable: false,
    chefInstruction:
      "One batch, split evenly — slice the bread and dice the tomato once for both plates.",
    customerDialogue: "We're sharing tonight — one plate each, please.",
    basePayment: 140,
    unlockLevel: 29,
  },

  // ───────────────────────── Chapter 4 — French Bistro ─────────────────────────
  {
    id: "camp-baguette-rounds",
    name: "Baguette Rounds",
    emoji: "🥖",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "baguette",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Slice the baguette into even rounds.",
    customerDialogue: "Just the bread, sliced properly.",
    basePayment: 110,
    unlockLevel: 31,
  },
  {
    id: "camp-french-onion-base",
    name: "French Onion Base",
    emoji: "🧅",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "onion",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "celery",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: true,
    chefInstruction: "Slice the onion thin, then julienne the celery alongside it.",
    customerDialogue: "The onion soup base, if it's started.",
    basePayment: 120,
    unlockLevel: 32,
  },
  {
    id: "camp-potato-veloute-base",
    name: "Potato Velouté Base",
    emoji: "🥔",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "potato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: true,
    chefInstruction: "Dice the potato evenly for the velouté.",
    customerDialogue: "The potato soup, please.",
    basePayment: 115,
    unlockLevel: 33,
  },
  {
    id: "camp-rock-minced-garlic-herb",
    name: "Rock Minced Garlic Herb",
    emoji: "🧄",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "garlic",
        technique: "rockMince",
        resultingState: "minced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction: "Rock-mince the garlic fine, rocking the blade heel-to-tip.",
    customerDialogue: "The garlic, minced fine — for the sauce.",
    basePayment: 125,
    unlockLevel: 34,
  },
  {
    id: "camp-chiffonade-herb-garnish",
    name: "Chiffonade Herb Garnish",
    emoji: "🌿",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "basil",
        technique: "chiffonade",
        resultingState: "ribboned",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Roll the basil and chiffonade it into fine ribbons.",
    customerDialogue: "A little herb garnish, please — nothing heavy.",
    basePayment: 128,
    unlockLevel: 35,
  },
  {
    id: "camp-mushroom-garlic-saute-prep",
    name: "Mushroom & Garlic Sauté Prep",
    emoji: "🍄",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "mushroom",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "garlic",
        technique: "rockMince",
        resultingState: "minced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: true,
    chefInstruction: "Slice the mushrooms, then rock-mince the garlic through them.",
    customerDialogue: "The sautéed mushrooms, please.",
    basePayment: 135,
    unlockLevel: 36,
  },
  {
    id: "camp-spinach-fennel-chiffonade-plate",
    name: "Spinach & Fennel Chiffonade Plate",
    emoji: "🥬",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "spinach",
        technique: "chiffonade",
        resultingState: "ribboned",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "fennel",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: false,
    chefInstruction: "Chiffonade the spinach into ribbons, then slice the fennel alongside it.",
    customerDialogue: "Something green and delicate.",
    basePayment: 140,
    unlockLevel: 37,
  },
  {
    id: "camp-asparagus-carrot-precision-plate",
    name: "Asparagus & Carrot Precision Plate",
    emoji: "🥕",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "asparagus",
        technique: "slice",
        resultingState: "sliced",
        destinationIds: ["plate"],
      },
      {
        ingredientId: "carrot",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["plate"],
      },
    ],
    destinations: [PLATE],
    batchable: true,
    chefInstruction: "Slice the asparagus, then julienne the carrot to the same fine standard.",
    customerDialogue: "Precision, please — this table notices the cut.",
    basePayment: 150,
    unlockLevel: 38,
  },
  {
    id: "camp-celery-potato-prep",
    name: "Celery & Potato Prep",
    emoji: "🥔",
    cuisineId: "french",
    authenticity: "A",
    components: [
      {
        ingredientId: "celery",
        technique: "julienne",
        resultingState: "julienned",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "potato",
        technique: "dice",
        resultingState: "diced",
        destinationIds: ["bowl"],
      },
      {
        ingredientId: "garlic",
        technique: "rockMince",
        resultingState: "minced",
        destinationIds: ["bowl"],
      },
    ],
    destinations: [BOWL],
    batchable: false,
    chefInstruction:
      "Julienne the celery, dice the potato, then rock-mince the garlic through both.",
    customerDialogue: "The full prep, please — everything the recipe calls for.",
    basePayment: 165,
    unlockLevel: 39,
  },
];

export function getCampaignRecipe(id: string): RecipeDefinition | undefined {
  return CAMPAIGN_RECIPES.find((r) => r.id === id);
}
